### PR TITLE
[FIX][I] #445 Enforce correct order of activities after file creation

### LINKED ISSUE #445: Follow Mode does not handle file creation correctly
When the followee creates a new file during the follow mode, the follower does not open the file automatically.

The follower is throwing an exception internally.
<details><summary>Exception</summary>
<p>

```Java
ERROR 16:29:37,857 [AWT-EventQueue-0] (SarosSession.java:195) error while invoking active activity consumer: de.fu_berlin.inf.dpp.editor.FollowModeManager$3@7c635aa0, activity: EditorActivity(type: ACTIVATED, path: SPath [project=IntelliJProjectImpl : SharedModule, projectRelativePath=src/plot_ha/other/test/ha/Test3.java])
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'resource' of de/fu_berlin/inf/dpp/intellij/session/SessionUtils.isShared must not be null
	at de.fu_berlin.inf.dpp.intellij.session.SessionUtils.$$$reportNull$$$0(SessionUtils.java)
	at de.fu_berlin.inf.dpp.intellij.session.SessionUtils.isShared(SessionUtils.java)
	at de.fu_berlin.inf.dpp.intellij.editor.LocalEditorManipulator.openEditor(LocalEditorManipulator.java:67)
	at de.fu_berlin.inf.dpp.intellij.editor.EditorManager.lambda$openEditor$3(EditorManager.java:836)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:652)
	at de.fu_berlin.inf.dpp.intellij.editor.EditorManager.executeInUIThreadSynchronous(EditorManager.java:812)
	at de.fu_berlin.inf.dpp.intellij.editor.EditorManager.openEditor(EditorManager.java:836)
	at de.fu_berlin.inf.dpp.editor.FollowModeManager$3.receive(FollowModeManager.java:118)
	at de.fu_berlin.inf.dpp.activities.EditorActivity.dispatch(EditorActivity.java:106)
	at de.fu_berlin.inf.dpp.session.AbstractActivityConsumer.exec(AbstractActivityConsumer.java:81)
	at de.fu_berlin.inf.dpp.editor.FollowModeManager$3.exec(FollowModeManager.java:106)
	at de.fu_berlin.inf.dpp.session.internal.SarosSession$2.execute(SarosSession.java:193)
	at de.fu_berlin.inf.dpp.session.internal.ActivityHandler$3.run(ActivityHandler.java:339)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:35)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

</p>
</details>

My guess would be that the follower is trying to access/open the file before it was created locally. This still has to be investigated.

### PR DESCRIPTION
**Pull request by tobous**
#### [FIX][I] #445 Avoid opening editor before sending file creation activity

Moves opening the created file in an editor after the file creation
activity was dispatched. This is necessary as the Saros otherwise
dispatches the editor opened activity before the file creation activity,
meaning the other participants receive an editor activation activity for
a non-existent resource. This is especially troublesome when the other
participant is following the user that created the file, as they then
automatically try to react to the editor activation activity by also
opening the (non-existent) file.

Fixes #445.

#### [REFACTOR][I] Do minor cleanup in LocalFilesystemModificationHandler

Moves the javadoc concerning the listener behavior from the handler
methods to the javadoc of the listener methods.

Fixes typo in method name 'generateResourceMoveActivity'.

Adds comment for IntelliJ code inspection to ignore the switch case in
generateRenamingResourceMoveActivity(...) having to few cases. The
switch gives us flexibility if we ever decide to add more cases and it
does not reduce the readability by much.

### CODE REVIEW

File: intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java [hunk 1]
```diff
@@ -259,11 +287,13 @@ private void generateResourceCreationActivity(@NotNull VirtualFileEvent virtualF
...
           new FileActivity(
               user, Type.CREATED, FileActivity.Purpose.ACTIVITY, path, null, content, charset);
-
-      editorManager.openEditor(path, false);
     }
 
     dispatchActivity(activity);
+
+    if (!createdVirtualFile.isDirectory()) {
+      editorManager.openEditor(path, false);
```
Comment (srossbach) [inline intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java]: I still does not understand why the editor is opened here. Is the open call a "connect" call so we now that we now must track changes or it is really opened in the UI ?

Comment (tobous) [reply intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java]: It is both. To only open an editor, [`ProjectAPI.openEditor(...)`](https://github.com/saros-project/saros/blob/master/intellij/src/saros/intellij/editor/ProjectAPI.java#L59) can be used.
The methods `LocalEditorManager.openEditor(...)` and `LocalEditorHandler.openEditor(...)` both open the editor and set it up for Saros (adding it to the editor pool and registering handlers; the handler registration gets removed with 1156cb640cbb7b6d3227abb3101882945f07e4a1 as part of #446).

The problem is that I am not aware of a method that gives us arbitrary editor objects for open editors. The method described [here](https://www.jetbrains.org/intellij/sdk/docs/tutorials/editor_basics/working_with_text.html#getting-an-instance-of-the-active-editor) can give us the active editor, but that is about it.

So, to add the editor to the editor pool, we either have to use `ProjectAPI.openEditor(...)`, which automatically opens an editor for the given VirtualFile if it is not already open, or wait until the editor is opened so that we can get the object from the listener.

Comment (tobous) [reply intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java]: An approach to remove this duality would be to remove the editor pool and always resolve the resource for the editor directly if necessary. Will look into whether this is plausible.

**Comment by tobous** [comment]
Rebased onto current base PR without any interaction.

**Comment by tobous** [comment]
Rebased onto current master without any interaction.

File: intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java (hunk 1 above)
Comment (tobous) [reply intellij/src/saros/intellij/eventhandler/filesystem/LocalFilesystemModificationHandler.java]: Removing the EditorPool seems plausible, but it is somewhat of a hassle as it is used a lot in `EditorManager`. I don't think it is currently worth it to invest time into removing it.
