### PR TITLE
Move Saros/I to application context

### LINKED ISSUE #76: IntellijSarosLifecycle not Singleton
Currently, the IntellijSarosLifecycle is not a singleton thus it's possible to instantiate it multiple times. This can be reproduced for example by closing and reopening a project in IntelliJ and lead to faulty behaviour. A consequence for instance can be that the existence of multiple XMPPConnectionServices with some parts of Saros/I using one and other parts the other instance(s).

IntellijSarosLifecycle holds a reference to a project as a member, so considerations how to deal with reopening another project have to be made. For a first conversation about this, see [this patch](http://saros-build.imp.fu-berlin.de/gerrit/#/c/3120/)

Reported by: denvercoder21

Original Ticket: [dpp/bugs/879](https://sourceforge.net/p/dpp/bugs/879)

### LINKED ISSUE #394: Saros/I plugin causes assertion error when closing and then re-opening project
When closing the current project and re-opening it (or another project), the Saros plugin causes an assertion error trying to use the old project object. (The full stacktrace is given below.) This most likely happens because the project object is held in the saros plugin context.

The project object is put into the plugin context through the [IntellijProjectLifecycle](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/IntellijProjectLifecycle.java), which in turn calls the [SarosIntellijContextFactory](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/context/SarosIntellijContextFactory.java#L105). The lifecycle is instantiated by the [SarosComponent](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/SarosComponent.java#L50), which hooks into IntelliJ through the [plugin.xml](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.intellij/META-INF/plugin.xml#L31)

The question now is why this context is not cleaned up between the project changes. Saros/I should be a project level component, meaning a new instance of the plugin should be created once the new project is opened, then also containing the correct project object.

#### Stacktrace
```Java
java.lang.AssertionError: Already disposed: Project (Disposed) HostTestProject
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:248)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:246)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:239)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:45)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:42)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:30)
	at com.intellij.openapi.roots.ProjectFileIndex.getInstance(ProjectFileIndex.java:44)
	at com.intellij.openapi.roots.ProjectFileIndex$SERVICE.getInstance(ProjectFileIndex.java:38)
	at com.intellij.openapi.module.ModuleUtilCore.findModuleForFile(ModuleUtilCore.java:71)
	at de.fu_berlin.inf.dpp.intellij.filesystem.VirtualFileConverter.convertToResource(VirtualFileConverter.java:63)
	at de.fu_berlin.inf.dpp.intellij.filesystem.VirtualFileConverter.convertToSPath(VirtualFileConverter.java:46)
	at de.fu_berlin.inf.dpp.intellij.editor.LocalEditorHandler.activateEditor(LocalEditorHandler.java:221)
	at de.fu_berlin.inf.dpp.intellij.editor.LocalEditorStatusChangeHandler.generateEditorActivatedActivity(LocalEditorStatusChangeHandler.java:150)
	at de.fu_berlin.inf.dpp.intellij.editor.LocalEditorStatusChangeHandler.access$300(LocalEditorStatusChangeHandler.java:18)
	at de.fu_berlin.inf.dpp.intellij.editor.LocalEditorStatusChangeHandler$1.selectionChanged(LocalEditorStatusChangeHandler.java:44)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy101.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$fireSelectionChanged$16(FileEditorManagerImpl.java:1584)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$5$1.run(FileEditorManagerImpl.java:1033)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$2(FocusManagerImpl.java:199)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3094)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:183)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:132)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:190)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:196)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:63)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$5.run(FileEditorManagerImpl.java:1030)
	at com.intellij.openapi.util.BusyObject$Impl$Simple.execute(BusyObject.java:108)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.notifyPublisher(FileEditorManagerImpl.java:1026)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.fireSelectionChanged(FileEditorManagerImpl.java:1584)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$setCurrentWindow$2(EditorsSplitters.java:599)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.setCurrentWindow(EditorsSplitters.java:608)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.setEditor(EditorWindow.java:722)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$9(FileEditorManagerImpl.java:913)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:864)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:205)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:588)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:250)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:203)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:439)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:414)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:245)
	at com.intellij.ide.RecentProjectsManagerBase.doOpenProject(RecentProjectsManagerBase.java:579)
	at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:72)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$3.onClick(RecentProjectPanel.java:156)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### PR DESCRIPTION
**Pull request by tobous**
#### [INTERNAL][I] Add shared project to SharedIDEContext

Adjusts the existing logic to add the needed shared project object to
the SharedIDEContext when a session is started.

Subsequently removes the workaround adding the plugin context project
object to the SharedIDEContext if no other project object is given. The
workaround is no longer needed as all necessary calls starting a session
now correctly set the shared project object.

#### [INTERNAL][I] Move plugin to application context

Makes the Saros/I plugin an application level plugin, meaning a single
instance will be loaded when the application is started. This plugin
instance is shared by all open projects.

Fixes #76. Fixes #394.

Also makes the IntellijProjectLifecycle really a singleton and removes
the project object from the lifecycle.

Subsequently removes the project object from the plugin context as this
is now completely handled by the SharedIDEContext. Also removes the
project object from the affected test cases.

### CODE REVIEW

File: intellij/src/saros/intellij/SarosComponent.java [hunk 1]
```diff
@@ -3,27 +3,25 @@
...
 import org.apache.log4j.helpers.LogLog;
-import org.jetbrains.annotations.NotNull;
 
 /**
- * Component that is initalized when a project is loaded. It initializes the logging, shortcuts and
+ * Component that is initialized when a project is loaded. It initializes the logging, shortcuts and
  * the {@link IntellijProjectLifecycle} singleton.
  */
-public class SarosComponent implements com.intellij.openapi.components.ProjectComponent {
+public class SarosComponent {
```
Comment (srossbach) [inline intellij/src/saros/intellij/SarosComponent.java]: https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/openapi/components/ApplicationComponent.java

* Instead of {@link #initComponent()} please use {@link com.intellij.util.messages.MessageBus} and corresponding topics.
 * Instead of {@link #disposeComponent()} please use {@link com.intellij.openapi.Disposable}.

I would prefer to use such methods and not doing the heavy in the CTOR,

Looking at the code, is the session closed when you shutdown IntelliJ, i.e not stopping the session manually ?

Comment (tobous) [reply intellij/src/saros/intellij/SarosComponent.java]: > I would prefer to use such methods and not doing the heavy in the CTOR,

I also considered the approach (as it is actively requested by the documentation), but couldn't find a good topic to use. The way I understand it, the thought behind moving this to message bus calls is reducing the load while initializing the application/project, i.e. only load the plugins when they are really needed (as stated in the beginning of the javadoc).

But I am not sure our plugin fits into this model as it is not bound to a specific functionality but rather offers a service to the user. I could, in theory, change it so that the plugin is only loaded when the user opens a project for the first time, but I am not sure this really improves the behavior of the plugin. (Furthermore, this restricts us from starting a session from the project menu. Even though this is currently not implemented, it could be a useful entry point when wanting to accept sessions on entire projects, especially when they don't exist locally yet.)

This would still leave us with the option of using `initComponent()`, but I am not sure whether this is an improvement.

> Looking at the code, is the session closed when you shutdown IntelliJ, i.e not stopping the session manually ?

No, it is not (currently).

As far as I know, terminating IntelliJ triggers project closed listeners, which we can use for this purpose.
This logic was initially part of #539, but I decided to move it to a separate PR. Since that decision, I have worked on it a bit, but still couldn't find a good solution avoiding the synchronous session end (session end should not be called on the EDT, but I need to ensure that no activities for the closed project are handled; implementing this with a filter in the core did not prove as effective as initially thought). I will open a WIP PR for this logic, showing off the approach and further explaining the remaining issues.

We also don't handle the disposed case explicitly. My assumption was that the plugin is torn down automatically when the application is terminated/torn down.

Comment (tobous) [reply intellij/src/saros/intellij/SarosComponent.java]: @srossbach Do you have any issues with the current state of the PR (besides the  CTOR issue)? Otherwise, I would proceed with merging this.

If you would like, I can also open an issue for the CTOR issue so that we can keep it in mind (and have another look at it later on).

Comment (srossbach) [reply intellij/src/saros/intellij/SarosComponent.java]: Creating an issue stating that the session is not gracefully shutdown (it is not shutdown at all) when you close the IntelliJ IDE process should be ok.

Comment (tobous) [reply intellij/src/saros/intellij/SarosComponent.java]: Open #582 for this.

**Comment by tobous** [comment]
Rebased onto current master without any interaction.
