### PR TITLE
[E] Always Open Contact List for New Contact

### LINKED ISSUE #796: Contacts view does not open when connecting to account
The contact view in Saros/E stays closed when connecting to an account (or a contact comes online). This is a regression from the previous release `15.0.0` where this worked correctly.

### PR DESCRIPTION
**Pull request by stefaus**
#### [E] Always Open Contact List for New Contact

Always open the UI contact list when a new contact was presented by the
XMPPContactsService. This fixes #796 where this wasn't done after
connecting (introduced with changes for ContactService) and also fixes
an older STF Problem / UI Problem when the list stayed collapsed due to
be empty before.

#### [E] Remove Unnecessary Hook to Expand Contact List

### CODE REVIEW

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ eclipse/src/saros/ui/widgets/viewer/session/XMPPSessionDisplayComposite.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=4782334&bid=15930198)

**Comment by m273d15** [comment]
Nice, I will test this tomorrow on my Linux 👍

File: eclipse/src/saros/ui/widgets/viewer/session/XMPPSessionDisplayComposite.java [hunk 1]
```diff
@@ -33,33 +28,13 @@
...
 public final class XMPPSessionDisplayComposite extends SessionDisplayComposite {
 
-  private static final Logger LOG = Logger.getLogger(XMPPSessionDisplayComposite.class);
-
-  @Inject private ConnectionHandler connectionHandler;
   @Inject private XMPPContactsService contactsService;
 
-  private final IConnectionStateListener connectionListener =
-      (state, error) -> {
-        if (state == ConnectionState.CONNECTED || state == ConnectionState.NOT_CONNECTED) {
```
Comment (tobous) [inline eclipse/src/saros/ui/widgets/viewer/session/XMPPSessionDisplayComposite.java]: Why is this listener now unnecessary? It seems pretty useful to expand the view when a new connection gets established. (Expanding it on disconnection however is not that useful as.)

This does not seem directly connected to the other part of the PR as that logic only expands the view when a new contact is added. Is there another listener that already expands the contacts view when a new connection is established?

Comment (stefaus) [reply eclipse/src/saros/ui/widgets/viewer/session/XMPPSessionDisplayComposite.java]: Because it just works for the disconnect case and this case is not needed.

The contact list is de facto empty after connection start, and existing contacts on the roster are added via roster / ContactsService listener updates as `UpdateType.ADDED` in `SessionContentProvider` leading to expanding the contact list right after start.

So this deleted code has no implication and if a user decides to collapse the contact list in the mean time I don't think it should be open at disconnect.

**Comment by srossbach** [comment]
I just noticed that the RosterContentProvider does not longer update itself. This provider is used in another widget too. This design change was not documented at all.

**Comment by saros-infrastructure** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ eclipse/src/saros/ui/widgets/viewer/session/XMPPSessionDisplayComposite.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Saros/saros/pullRequest?prid=4782334&bid=15930198)
