### PR TITLE
Fix version mismatch notification and notification utils bug

### LINKED ISSUE #674: User not notified about session invitation failure when an error occurs.
Users are not notified that the session negotiation failed because of a version mismatch (the Saros version of the negotiation participants were not compatible). Instead, the negotiation just fails silently.

A better behavior would be to show a notification to the user stating this fact.

### PR DESCRIPTION
**Pull request by tobous**
#### [FIX][I] Fix project selection logic for notifications

Adjusts the notification panel logic to use the session project or, if
no such project is available, use the last focused project. This
guarantees that a project is always specified to guarantee that the
notification is always displayed as a pop-up.

Indirectly fixes a bug where the old logic requesting the Project object
directly from the plugin context was still used in
UIProjectUtils.getProjectFromSession(). This lead to the method always
returning null, even if a shared project was available.

Adds a method to check whether the shared IDE context is completely
initialized. This is needed as it is not guaranteed that the
notification logic is only called after the initialization. This is only
a workaround. The logic should be improved to better handle calls in the
uninitialized state.

Subsequently removes the method UIProjectUtils.getSharedProject() as it
is no longer used.

#### [FIX][I] #674 Show notification if outgoing session negotiation errors

Adjusts the logic in NegotiationHandler to display a user notification
when the outgoing session negotiation exist with an error status. This
is only a temporary fix. In the long-term, the usage of UIMonitoredJob
should be replaced by a generic implementation based on
ProgressMonitorAdater that handles all of these cases for all calls.

Fixes #674.

### CODE REVIEW

File: intellij/src/saros/intellij/ui/util/UIProjectUtils.java [hunk 1]
```diff
@@ -69,7 +58,13 @@ private Project getProjectFromSession() {
       return null;
     }
 
-    return currentSession.getComponent(Project.class);
+    SharedIDEContext sharedIDEContext = currentSession.getComponent(SharedIDEContext.class);
```
Comment (srossbach) [inline intellij/src/saros/intellij/ui/util/UIProjectUtils.java]: Nullcheck missing.

File: intellij/src/saros/intellij/ui/Messages.java [hunk 2]
```diff
@@ -85,10 +85,12 @@
   public static String ConnectButton_connect_to_new_account_title;
   public static String ConnectButton_connect_to_new_account_message;
 
-  public static String NegotiationHandler_canceled_invitation;
-  public static String NegotiationHandler_canceled_invitation_text;
-  public static String NegotiationHandler_error_during_invitation;
-  public static String NegotiationHandler_error_during_invitation_text;
+  public static String NegotiationHandler_session_local_error_title;
```
Comment (srossbach) [inline intellij/src/saros/intellij/ui/Messages.java]: I do not know if it is a good decision to mix session_negotiation and invention. Just stick to one wording (I do not prefer session negotiation and not invitation)

File: intellij/src/saros/core/ui/eventhandler/NegotiationHandler.java [hunk 3]
```diff
@@ -136,33 +136,41 @@ protected IStatus run(IProgressMonitor monitor) {
...
+
             return new Status(
                 IStatus.ERROR, SarosComponent.PLUGIN_ID, negotiation.getErrorMessage());
           case OK:
             break;
           case REMOTE_CANCEL:
             NotificationPanel.showInformation(
-                MessageFormat.format(Messages.NegotiationHandler_canceled_invitation_text, peer),
-                Messages.NegotiationHandler_canceled_invitation);
+                MessageFormat.format(
```
Comment (srossbach) [inline intellij/src/saros/core/ui/eventhandler/NegotiationHandler.java]: Duplicated code. Maybe you can declare: String title, message at the top of the method an then assign the values. This is easier to read because you generate the message e.g 2 times here in this section.

File: intellij/src/saros/intellij/ui/util/UIProjectUtils.java (hunk 1 above)
Comment (tobous) [reply intellij/src/saros/intellij/ui/util/UIProjectUtils.java]: Done.

File: intellij/src/saros/core/ui/eventhandler/NegotiationHandler.java (hunk 3 above)
Comment (tobous) [reply intellij/src/saros/core/ui/eventhandler/NegotiationHandler.java]: Done.

File: intellij/src/saros/intellij/ui/Messages.java (hunk 2 above)
Comment (tobous) [reply intellij/src/saros/intellij/ui/Messages.java]: Done.
