### PR TITLE
[FIX][I] #703 Use IntelliJ util to parse URI

### LINKED ISSUE #703: Windows: "Use existing module" fails in Saros/I
**Describe the bug**
Sharing a project with the option "Use existing module" fails with the following message if the client (not host) side is windows:
```
ERROR 13:18:43,982 [ApplicationImpl pooled thread 5] (Negotiation.java:357) IPN [remote side: dev8_alice_stf@saros-con.imp.fu-berlin.de/Saros] unknown error
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file://C:/Users/kelvin/IdeaProjects/untitled1/SharedModule
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at saros.intellij.negotiation.ModuleConfigurationInitializer.relativize(ModuleConfigurationInitializer.java:201)
	at saros.intellij.negotiation.ModuleConfigurationInitializer.lambda$configurationDiffers$3(ModuleConfigurationInitializer.java:178)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at saros.intellij.negotiation.ModuleConfigurationInitializer.configurationDiffers(ModuleConfigurationInitializer.java:179)
	at saros.intellij.negotiation.ModuleConfigurationInitializer.applyModuleConfiguration(ModuleConfigurationInitializer.java:126)
	at saros.intellij.negotiation.ModuleConfigurationInitializer.access$000(ModuleConfigurationInitializer.java:39)
	at saros.intellij.negotiation.ModuleConfigurationInitializer$1.resourcesAdded(ModuleConfigurationInitializer.java:51)
	at saros.session.internal.SessionListenerDispatch.resourcesAdded(SessionListenerDispatch.java:56)
	at saros.session.internal.SarosSession.addSharedResources(SarosSession.java:278)
	at saros.negotiation.AbstractIncomingProjectNegotiation.run(AbstractIncomingProjectNegotiation.java:207)
	at saros.intellij.ui.wizards.AddProjectToSessionWizard$7.run(AddProjectToSessionWizard.java:616)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
1. Start a session with a windows participant
2. the windows user uses the option "use existing module"

### PR DESCRIPTION
**Pull request by tobous**
Uses VfsUtil.toUri(String) to correctly parse the "URL" returned by
getUrl() calls on VFS objects.

This is needed as the "URI" format does not adhere to the standard on
Windows machines, leading to issues when trying to parse it directly.
This is discussed in the PR #704 and the IntelliJ bugtracker entry
"https://youtrack.jetbrains.com/issue/IDEA-146869".

Fixes #703. Adjustment of initial fix PR #704.

### CODE REVIEW

**Comment by tobous** [comment]
Confirmed correctly parsing on Windows and Linux. Don't have an macOS system, but I would hope this is *now* also covered by the IntelliJ utility method parsing their internal URIs.

File: intellij/src/saros/intellij/negotiation/ModuleUtils.java [hunk 1]
```diff
@@ -28,10 +27,18 @@
   @Nullable
   static Path getRelativeRootPath(@NotNull Path basePath, @NotNull SourceFolder sourceFolder) {
     String sourcePath = sourceFolder.getUrl();
+
+    // Workaround to convert the Intellij "URI" to a real URI
```
Comment (m273d15) [inline intellij/src/saros/intellij/negotiation/ModuleUtils.java]: Is this still a workaround? Even if it is debatable practice to work with an own URI definition in intellij, we are using the APIs as intended and as far as I understand the APIs are working as expected. My perception is that this not a workaround anymore.
(Might be a bit pedantic and irrelevant. Therefore, approve :+1:)

Comment (tobous) [reply intellij/src/saros/intellij/negotiation/ModuleUtils.java]: I would still like to mention the fact that their "URL" is not actually a standard URI as this might be an important detail for someone having a look at the logic later on. I don't think the word "workaround" makes a big difference here, but I can remove it if you prefer.

Comment (m273d15) [reply intellij/src/saros/intellij/negotiation/ModuleUtils.java]: You don't have to remove it.
